[package]
name = "blackrock2"
version = "0.1.0"
edition = "2021"
description = "A rust port of the Blackrock2 cipher"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Vrtgs/blackrock2/"

[dependencies]
rand = "0.9.0-alpha.2"